StartupsPoleEmploi/anotea

backend/routes/backoffice/financer.js, backend/routes/backoffice/login.js, backoffice/src/App.js, backoffice/src/components/backoffice/Header.js, backoffice/src/lib/financerService.js
=> BO OF : Title for connected OF.

backend/jobs/import/trainee/traineeImporter.js
- empty lines are ignored in dry mode
- allow dry mode whereas file already imported
=> Trainee Import IDF : ignore empty lines

backend/components/regions.js, backend/jobs/import/trainee/handlers/poleEmploiCSVHandler.js, backend/jobs/import/trainee/index.js, backend/jobs/import/trainee/traineeImporter.js, backend/package-lock.json, backend/package.json
=> trainee import (dry run) : stop process if an error occurs

backend/routes/backoffice/login.js
This reverts commit f7527c8a727be5c9604252d6ae251043aedfa561.
=> Revert "fix legacy login to BO"

backend/config/default.json, backend/jobs/import/trainee/index.js, backend/test/integration/jobs/import/trainee/poleEmploiCSVHandler-test.js
- Ajout de la region PACA
- Correction d'un problème de timezone dans le script d'import des stagiaires
=> Add PACA into active regions

backend/config/custom-environment-variables.json, backend/config/default.json, backend/jobs/mailing/account/newOrganismeMailer.js, backend/jobs/mailing/account/resend.js, backend/jobs/mailing/campaign/mailerCampaign.js, backend/jobs/mailing/campaign/mailerCampaignManualResend.js, backend/jobs/mailing/campaign/mailerCampaignResend.js, backend/jobs/mailing/campaign/mailerCampaignRetry.js, backend/jobs/mailing/notification-of/mailerOrganismeWithCommentNonRead.js
Can be configured with ANOTEA_APP_MAILER_LIMIT
=> Send a single email by default

backend/jobs/import/account/importers/kairosAccountImporter.js, backend/jobs/import/trainee/handlers/ileDeFranceCSVHandler.js, backend/jobs/import/trainee/handlers/poleEmploiCSVHandler.js, backend/package-lock.json, backend/package.json, backend/test/integration/jobs/import/account/kairosAccountImporter-test.js, backend/test/integration/jobs/import/trainee/ileDeFranceCSVHandler-test.js, backend/test/integration/jobs/import/trainee/poleEmploiCSVHandler-test.js
=> Fix date timezone issue

backend/src/jobs/data/indexes/allIndexes.js
Le profiler a été activé pour trouver slow queries: `db.setProfilingLevel(1, { slowms: 125 })`.
=> Add missing indexes

questionnaire/src/components/ChampCommentaire.scss, questionnaire/src/components/Commentaire.jsx, questionnaire/src/components/Commentaire.scss, questionnaire/src/components/Header.jsx, questionnaire/src/components/NoteMoyenne.jsx, questionnaire/src/components/NoteMoyenne.scss, questionnaire/src/components/Notes.jsx, questionnaire/src/components/Stars.jsx, questionnaire/src/components/footer.scss, questionnaire/src/components/note.scss, questionnaire/src/components/stars.scss
=> polish CSS + half stars + fix note moyenne display

backend/src/http/routes/backoffice/stats.js, backoffice/src/components/backoffice/financer/stats/Dashboard.js, backoffice/src/components/backoffice/financer/stats/Graph.js, backoffice/src/components/backoffice/financer/stats/Table.js
add accumulated stats
don't show empty graph/table
add advice count on table
fix connected organisation rate
change title wording
=> Stats backoffice financeur

backend/src/http/routes/backoffice/export.js, backoffice/src/components/backoffice/common/deprecated/AdviceRates.js, backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
fix export.
fix rates undefined error.
=> Add qualification column for PE.

backend/src/http/routes/backoffice/moderateur/gestion-organismes.js, backend/test/integration/http/routes/backoffice/gestion-organismes-test.js, backoffice/src/components/backoffice/common/Header.jsx, backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.jsx, backoffice/src/components/backoffice/moderateur/moderation/AvisReponsesPanel.jsx
search OF by name, siret and email.
fix bad wording.
=> search OF by name, siret and email in the gestion des organismes panel

backend/config/default.json
Permettrait d'éviter le blacklistage chez icloud et d'autres
=> update FROM email

backend/src/common/components/sentry.js, backend/src/http/server.js
=> Add requestId to each request and send it to Sentry

docker-compose.override.yml, misc/efk/elasticsearch/Dockerfile, misc/efk/elasticsearch/app/elasticsearch.yml, misc/efk/fluentbit/Dockerfile, misc/efk/fluentbit/conf/fluent-bit.conf, misc/efk/fluentbit/conf/parsers.conf, misc/efk/fluentbit/conf/plugins.conf, misc/efk/kibana/Dockerfile, misc/efk/kibana/app/kibana.yml
Permet de démarrer et de configurer une stack ELK.
L'idée est d'avoir un ecosystème qui se rapproche de celui de la production.
=> Allow EFK stack to be started locally

backend/src/common/components/stats.js, backend/src/http/routes/api/stats-routes.js, backend/src/http/routes/front/front-routes.js, backend/src/http/views/front/stats.ejs, backend/src/jobs/data/indexes/mongoIndexes.js
=> Add stats about formations and avis

WIDGET.md, backend/.gitignore, backend/Dockerfile, backend/package-lock.json, backend/package.json, backend/src/http/public/static/js/widget/anotea-widget.js, backend/src/http/routes/front/front-routes.js, backend/src/http/server.js, backend/src/http/views/front/doc/widget-tests.ejs, backend/src/http/views/front/doc/widget.ejs, widget/package-lock.json, widget/package.json
=> Move anotea-widget.js to be served has a static backend resource

backend/src/http/routes/api/swagger.yml, backend/src/http/routes/api/v1/actions-routes.js, backend/src/http/routes/api/v1/avis-routes.js, backend/src/http/routes/api/v1/formations-routes.js, backend/src/http/routes/api/v1/organismes-formateurs-routes.js, backend/src/http/routes/api/v1/sessions-routes.js, backend/src/http/routes/api/v1/utils/validators.js, backend/test/integration/http/routes/api/v1/actions-routes-test.js, backend/test/integration/http/routes/api/v1/avis-routes-test.js, backend/test/integration/http/routes/api/v1/formations-routes-test.js, backend/test/integration/http/routes/api/v1/organismes-formateurs-routes-test.js, backend/test/integration/http/routes/api/v1/sessions-routes-test.js
Ces nouvelles routes vont permettre d'utiliser la pagination dans le widget
=> Add /api/v1/*/avis

backoffice/package-lock.json, backoffice/package.json, backoffice/src/components/backoffice/organisation/Graphes.js
=> adding label to pie charts

backend/src/common/components/regions.js, backend/src/http/routes/api/regions-routes.js, backend/src/http/server.js, backend/test/integration/http/routes/api/regions-routes-test.js
=> Add routes to get all regions

backend/src/http/routes/api/backoffice/moderateur/moderation-routes.js, backend/test/integration/http/routes/api/backoffice/moderation-routes-test.js
This reverts commit b01eb91c5f77ab6810ba14529158163c045af1f8.
=> Revert "Deactivate sendReponseRejeteeNotification"

docker-compose.override.yml, docker-compose.test.yml, docker-compose.yml
see https://github.com/docker/compose/issues/4513
3.x = swarn/stack
2.x = docker-compose
thanks to @nsitbon
=> Use docker-compose v2.4

docker-compose.override.yml, docker-compose.yml
This reverts commit 78f2ddd7460cdb791eba168a8744f64e3dc78b05.
=> Add memory limits into docker-compose

backend/config/default.json, backend/src/smtp/mailer.js
This reverts commit b36fef26ae55b25e040c985f53241af0d513b965.
=> Revert "change smtp FROM address"

backend/src/http/routes/api/backoffice/financeur/financeur-routes.js, backoffice/src/App.jsx, backoffice/src/components/backoffice/common/FinanceurHeaderItems.jsx, backoffice/src/components/backoffice/common/Header.jsx, backoffice/src/components/backoffice/common/Stars.jsx, backoffice/src/components/backoffice/common/Stars.scss, backoffice/src/components/backoffice/financeur/Avis.jsx, backoffice/src/components/backoffice/financeur/FiltersResume.jsx, backoffice/src/components/backoffice/financeur/FinancerPanel.jsx, backoffice/src/components/backoffice/financeur/FinancerPanel.scss, backoffice/src/components/backoffice/financeur/FinanceurRoutes.jsx, backoffice/src/components/backoffice/financeur/Resume.jsx, backoffice/src/components/backoffice/financeur/StatistiquesPanel.jsx, backoffice/src/components/backoffice/financeur/Titre.jsx, backoffice/src/components/backoffice/financeur/filters/filter.jsx, backoffice/src/components/backoffice/financeur/service/financeurService.js
- Lors de la cnx d'une DR PE : on restitue tous les avis de l'ensemble des financeurs.
- La DR en question pourra par la suite chosir de restituer soit ses avis soit les avis d'un financeur qu'elle selectionnera dans la liste des financeurs.
-Implementation des parties : filtres, onglets, resumes, avis et pagination
- Some refacto...
=> BO financeur: new design

backend/src/http/routes/api/questionnaire/questionnaire-routes.js, backend/src/http/routes/api/questionnaire/utils/badwords.js, backend/src/http/routes/api/questionnaire/utils/badwords.txt, backend/test/integration/http/routes/api/questionnaire-routes-test.js, backend/test/unit/badwords-test.js, questionnaire/src/components/pages/questionnaire/commentaire/Commentaire.jsx
J'ai fait un tri du fichier avec la commande
`cat src/http/routes/api/questionnaire/utils/badwords.txt | sort`
=> Add new badwords

backend/src/jobs/data/dataset/index.js, backend/src/jobs/data/dataset/tasks/createAvis.js, backend/src/jobs/data/dataset/tasks/createStagiaires.js, backend/src/jobs/data/dataset/tasks/emulateBackofficeActions.js, backoffice/src/components/common/Pastille.jsx, backoffice/src/components/financeur/FinanceurPage.jsx, backoffice/src/components/organisme/OrganismePage.jsx
Permet de tester plus facilement les backoffices
=> Rework dataset generator script

backoffice/package-lock.json, backoffice/package.json, backoffice/public/index.html, backoffice/src/index.js, questionnaire/package-lock.json, questionnaire/package.json, questionnaire/public/index.html, questionnaire/src/index.js, widget/package-lock.json, widget/package.json
=> Add ES2017/2018 polyfills

backend/src/http/views/front/faq_organismes.ejs
j'ai carrément supprimé une question et sa réponse. j'espère que ça n'a pas d'impact
=> modif wording

backoffice/src/components/anonymous/ContactRegion.jsx, backoffice/src/components/anonymous/ContactRegion.scss, backoffice/src/components/anonymous/LoginPage.jsx, backoffice/src/components/common/page/form/Select.jsx, backoffice/src/services/anonymous.js
=> Modal that select region for mailto

backend/src/http/api/backoffice/login-routes.js, backend/src/http/api/kairos/kairos-routes.js, ui/src/backoffice/components/anonymous/LoginPage.jsx
This reverts commit f584e9666d8c1d1d395a359afcfc8ca4e1b7c4c0.
=> Revert "désactiver API connexion en recette"
